version: 2
updates:
  # GitHub Actions 更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker 依賴更新
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
      include: "scope"

  # 檢查所有子目錄的 Docker 文件
  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/mariadb"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/redis"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/POSTGRES"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
      include: "scope"
