name: elfnginxhaproxy
services:
  elf-nginx:
    container_name: elf-nginx
    image: tw199501/nginx:1.29.3
    restart: unless-stopped
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /opt/nginx-stack/nginx:/etc/nginx
      - /opt/nginx-stack/nginx-logs:/var/log/nginx
    networks:
      - elf-internal

  haproxy:
    container_name: haproxy
    image: tw199501/haproxy:trixie
    restart: unless-stopped
    depends_on:
      - elf-nginx
    ports:
      - "80:80"
      - "443:443"
      - "8404:8404"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - elf-internal

networks:
  elf-internal:

