name: haprox
services:
  elf-nginx:
    container_name: elf-nginx
    image: tw199501/nginx:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /etc/nginx:/etc/nginx
      - /usr/lib/nginx/modules:/usr/lib/nginx/modules
      - /var/log/nginx:/var/log/nginx
      - /var/cache/nginx:/var/cache/nginx
      - /usr/share/GeoIP:/usr/share/GeoIP
      - /usr/share/modsecurity-crs:/usr/share/modsecurity-crs
      - /opt/stacks/haprox/keepalived:/opt/keepalived
    networks:
      - elf-internal
  haproxy:
    container_name: haproxy
    image: tw199501/haproxy:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Taipei
    depends_on:
      - elf-nginx
    ports:
      - 80:80
      - 443:443
      - 8404:8404
    volumes:
      - /opt/stacks/haprox/haproxy:/usr/local/etc/haproxy
    networks:
      - elf-internal
networks:
  elf-internal: null
