services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ${MSSQL_CONTAINER_NAME}
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      MSSQL_PID: "${MSSQL_PID}"
      MSSQL_COLLATION: "${MSSQL_COLLATION}"
      MSSQL_AGENT_ENABLED: "${MSSQL_AGENT_ENABLED}"
      MSSQL_TLS_CIPHER_SUITES: "${MSSQL_TLS_CIPHER_SUITES}"
      TZ: "${TZ}"
    ports:
      - "${MSSQL_HOST_PORT}:1433"
    volumes:
      - ${MSSQL_DATA_DIR_HOST}:/var/opt/mssql
      - ${MSSQL_CERT_DIR_HOST}:/etc/mssql/certs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '${MSSQL_LIMIT_CPU}'
          memory: ${MSSQL_LIMIT_MEM}
        reservations:
          cpus: '${MSSQL_RESERVE_CPU}'
          memory: ${MSSQL_RESERVE_MEM}
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${MSSQL_SA_PASSWORD}", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
